//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vychislenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Зверь.
    /// </summary>
    // *** Start programmer edit section *** (Зверь CustomAttributes)

    // *** End programmer edit section *** (Зверь CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗверьE", new string[] {
            "НазваниеЖ as \'Название Ж\'"})]
    [View("ЗверьL", new string[] {
            "НазваниеЖ as \'Название Ж\'"})]
    public class Зверь : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеЖ;
        
        private IIS.Vychislenie.Лес fЛес;
        
        // *** Start programmer edit section *** (Зверь CustomMembers)

        // *** End programmer edit section *** (Зверь CustomMembers)

        
        /// <summary>
        /// НазваниеЖ.
        /// </summary>
        // *** Start programmer edit section *** (Зверь.НазваниеЖ CustomAttributes)

        // *** End programmer edit section *** (Зверь.НазваниеЖ CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеЖ
        {
            get
            {
                // *** Start programmer edit section *** (Зверь.НазваниеЖ Get start)

                // *** End programmer edit section *** (Зверь.НазваниеЖ Get start)
                string result = this.fНазваниеЖ;
                // *** Start programmer edit section *** (Зверь.НазваниеЖ Get end)

                // *** End programmer edit section *** (Зверь.НазваниеЖ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Зверь.НазваниеЖ Set start)

                // *** End programmer edit section *** (Зверь.НазваниеЖ Set start)
                this.fНазваниеЖ = value;
                // *** Start programmer edit section *** (Зверь.НазваниеЖ Set end)

                // *** End programmer edit section *** (Зверь.НазваниеЖ Set end)
            }
        }
        
        /// <summary>
        /// Зверь.
        /// </summary>
        // *** Start programmer edit section *** (Зверь.Лес CustomAttributes)

        // *** End programmer edit section *** (Зверь.Лес CustomAttributes)
        [PropertyStorage(new string[] {
                "Лес"})]
        [NotNull()]
        public virtual IIS.Vychislenie.Лес Лес
        {
            get
            {
                // *** Start programmer edit section *** (Зверь.Лес Get start)

                // *** End programmer edit section *** (Зверь.Лес Get start)
                IIS.Vychislenie.Лес result = this.fЛес;
                // *** Start programmer edit section *** (Зверь.Лес Get end)

                // *** End programmer edit section *** (Зверь.Лес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Зверь.Лес Set start)

                // *** End programmer edit section *** (Зверь.Лес Set start)
                this.fЛес = value;
                // *** Start programmer edit section *** (Зверь.Лес Set end)

                // *** End programmer edit section *** (Зверь.Лес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗверьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗверьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗверьE", typeof(IIS.Vychislenie.Зверь));
                }
            }
            
            /// <summary>
            /// "ЗверьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗверьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗверьL", typeof(IIS.Vychislenie.Зверь));
                }
            }
        }
    }
}
