//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vychislenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Лес.
    /// </summary>
    // *** Start programmer edit section *** (Лес CustomAttributes)

    // *** End programmer edit section *** (Лес CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЛесE", new string[] {
            "НазваниеЛ as \'Название Л\'"})]
    [View("ЛесL", new string[] {
            "НазваниеЛ as \'Название Л\'"})]
    public class Лес : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеЛ;
        
        private IIS.Vychislenie.DetailArrayOfСтрана fСтрана;
        
        // *** Start programmer edit section *** (Лес CustomMembers)

        // *** End programmer edit section *** (Лес CustomMembers)

        
        /// <summary>
        /// НазваниеЛ.
        /// </summary>
        // *** Start programmer edit section *** (Лес.НазваниеЛ CustomAttributes)

        // *** End programmer edit section *** (Лес.НазваниеЛ CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеЛ
        {
            get
            {
                // *** Start programmer edit section *** (Лес.НазваниеЛ Get start)

                // *** End programmer edit section *** (Лес.НазваниеЛ Get start)
                string result = this.fНазваниеЛ;
                // *** Start programmer edit section *** (Лес.НазваниеЛ Get end)

                // *** End programmer edit section *** (Лес.НазваниеЛ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.НазваниеЛ Set start)

                // *** End programmer edit section *** (Лес.НазваниеЛ Set start)
                this.fНазваниеЛ = value;
                // *** Start programmer edit section *** (Лес.НазваниеЛ Set end)

                // *** End programmer edit section *** (Лес.НазваниеЛ Set end)
            }
        }
        
        /// <summary>
        /// Лес.
        /// </summary>
        // *** Start programmer edit section *** (Лес.Страна CustomAttributes)

        // *** End programmer edit section *** (Лес.Страна CustomAttributes)
        public virtual IIS.Vychislenie.DetailArrayOfСтрана Страна
        {
            get
            {
                // *** Start programmer edit section *** (Лес.Страна Get start)

                // *** End programmer edit section *** (Лес.Страна Get start)
                if ((this.fСтрана == null))
                {
                    this.fСтрана = new IIS.Vychislenie.DetailArrayOfСтрана(this);
                }
                IIS.Vychislenie.DetailArrayOfСтрана result = this.fСтрана;
                // *** Start programmer edit section *** (Лес.Страна Get end)

                // *** End programmer edit section *** (Лес.Страна Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Лес.Страна Set start)

                // *** End programmer edit section *** (Лес.Страна Set start)
                this.fСтрана = value;
                // *** Start programmer edit section *** (Лес.Страна Set end)

                // *** End programmer edit section *** (Лес.Страна Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЛесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛесE", typeof(IIS.Vychislenie.Лес));
                }
            }
            
            /// <summary>
            /// "ЛесL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЛесL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЛесL", typeof(IIS.Vychislenie.Лес));
                }
            }
        }
    }
}
