//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vychislenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Страна.
    /// </summary>
    // *** Start programmer edit section *** (Страна CustomAttributes)

    // *** End programmer edit section *** (Страна CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтранаE", new string[] {
            "НазваниеС as \'Название С\'",
            "Лес.НазваниеЛ"})]
    [View("СтранаL", new string[] {
            "НазваниеС as \'Название С\'"})]
    public class Страна : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазваниеС;
        
        private IIS.Vychislenie.Лес fЛес;
        
        // *** Start programmer edit section *** (Страна CustomMembers)

        // *** End programmer edit section *** (Страна CustomMembers)

        
        /// <summary>
        /// НазваниеС.
        /// </summary>
        // *** Start programmer edit section *** (Страна.НазваниеС CustomAttributes)

        // *** End programmer edit section *** (Страна.НазваниеС CustomAttributes)
        [StrLen(255)]
        public virtual string НазваниеС
        {
            get
            {
                // *** Start programmer edit section *** (Страна.НазваниеС Get start)

                // *** End programmer edit section *** (Страна.НазваниеС Get start)
                string result = this.fНазваниеС;
                // *** Start programmer edit section *** (Страна.НазваниеС Get end)

                // *** End programmer edit section *** (Страна.НазваниеС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Страна.НазваниеС Set start)

                // *** End programmer edit section *** (Страна.НазваниеС Set start)
                this.fНазваниеС = value;
                // *** Start programmer edit section *** (Страна.НазваниеС Set end)

                // *** End programmer edit section *** (Страна.НазваниеС Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Vychislenie.Лес.
        /// </summary>
        // *** Start programmer edit section *** (Страна.Лес CustomAttributes)

        // *** End programmer edit section *** (Страна.Лес CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Лес"})]
        public virtual IIS.Vychislenie.Лес Лес
        {
            get
            {
                // *** Start programmer edit section *** (Страна.Лес Get start)

                // *** End programmer edit section *** (Страна.Лес Get start)
                IIS.Vychislenie.Лес result = this.fЛес;
                // *** Start programmer edit section *** (Страна.Лес Get end)

                // *** End programmer edit section *** (Страна.Лес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Страна.Лес Set start)

                // *** End programmer edit section *** (Страна.Лес Set start)
                this.fЛес = value;
                // *** Start programmer edit section *** (Страна.Лес Set end)

                // *** End programmer edit section *** (Страна.Лес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтранаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтранаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтранаE", typeof(IIS.Vychislenie.Страна));
                }
            }
            
            /// <summary>
            /// "СтранаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтранаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтранаL", typeof(IIS.Vychislenie.Страна));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Страна.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрана CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрана CustomAttributes)
    public class DetailArrayOfСтрана : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Vychislenie.DetailArrayOfСтрана members)

        // *** End programmer edit section *** (IIS.Vychislenie.DetailArrayOfСтрана members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Страна by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Страна.
        /// </summary>
        public DetailArrayOfСтрана(IIS.Vychislenie.Лес fЛес) : 
                base(typeof(Страна), ((ICSSoft.STORMNET.DataObject)(fЛес)))
        {
        }
        
        public IIS.Vychislenie.Страна this[int index]
        {
            get
            {
                return ((IIS.Vychislenie.Страна)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Vychislenie.Страна dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
